version: '3.8'
services:
  db:
    image: 'postgres:14.3-bullseye'
    container_name: tpFacultad
    ports:
      - "2300:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ../postgres/data:/var/lib/postgresql/data/pgdata